# Generated by Django 4.0.4 on 2022-05-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateTimeField()),
                ('eur', models.DecimalField(decimal_places=4, max_digits=6)),
                ('usd', models.DecimalField(decimal_places=4, max_digits=6)),
                ('jpy', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
