# Generated by Django 4.0.4 on 2022-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='jpy',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
