# Generated by Django 4.0.4 on 2022-05-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_alter_currency_jpy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='jpy',
            field=models.DecimalField(decimal_places=4, max_digits=17),
        ),
    ]
