# Generated by Django 4.0.4 on 2022-05-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_alter_currency_jpy'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='brl',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
